### ISSUE TITLE
[REQUEST] Change the Steamname to the RP Name from esx_identity

### ISSUE THREAD

**Issue by BoutProduction** [How-Bout-No/socialspot#2]
Hello, it would be nice if instead of the steamname your roleplay name is displayed

**Comment by How-Bout-No** [comment]
I've pushed e9a68da with experimental ESX_Identity support. This will probably need further testing as my test environment isn't properly set up for ESX.

If you don't mind, let me know how stable the ESX support is and any bugs you encounter that [aren't already known](https://github.com/How-Bout-No/socialspot/#known-bugs). Make sure you set `useESXIdentity = true` in the `config.lua`

**Comment by BoutProduction** [comment]
As soon as I start this version on my server, the server is automatically stopped!

Errorcode:

[104;39m> SocialSpot <[0;94m
Automatic updates are disabled.
[0m
Assertion failed: m_marks.find(mark) != m_marks.end() (../../../components/citizen-server-impl/src/ResourceFilesComponent.cpp: WriteMark: 35)
Stacktrace:

/proc/self/maps:
40724000-408d9000 rwxp 00000000 00:00 0 
4105b000-4113b000 rwxp 00000000 00:00 0 
41ba9000-41bb9000 rwxp 00000000 00:00 0 
44d2000000-44d2080000 rw-p 00000000 00:00 0 
193ffc00000-193ffc80000 rw-p 00000000 00:00 0 
29e6a168000-29e6a170000 rw-p 00000000 00:00 0 
2e294300000-2e294380000 rw-p 00000000 00:00 0 
42b22280000-42b22300000 rw-p 00000000 00:00 0 
7328a1be000-7328a1cc000 rwxp 00000000 00:00 0 
7328a1cc000-732ca1be000 ---p 00000000 00:00 0 
919e0c80000-919e0d00000 rw-p 00000000 00:00 0 
d1050100000-d1050180000 rw-p 00000000 00:00 0 
10d9a9a00000-10d9a9a80000 rw-p 00000000 00:00 0 
128980300000-128980380000 rw-p 00000000 00:00 0 
1502c8580000-1502c8600000 rw-p 00000000 00:00 0 
181457900000-181457980000 rw-p 00000000 00:00 0 
196efa400000-196efa480000 rw-p 00000000 00:00 0 
1ba323d80000-1ba323e00000 rw-p 00000000 00:00 0 
1c9a1fc80000-1c9a1fd00000 rw-p 00000000 00:00 0 
1d1315d80000-1d1315e00000 rw-p 00000000 00:00 0 
1e90f6b00000-1e90f6b80000 rw-p 00000000 00:00 0 
21f48e500000-21f48e580000 rw-p 00000000 00:00 0 
244de0000000-244de002f000 rw-p 00000000 00:00 0 
25ebddc80000-25ebddc83000 rw-p 00000000 00:00 0 
25ebddc83000-25ebddd00000 r--p 00000000 00:00 0 
Memory around native instruction pointer (0x7f81dcd33f6f):
0x7f81dcd33f5f  00 00 31 d2 bf 02 00 00 00 b8 0e 00 00 00 0f 05  ..1.............
0x7f81dcd33f6f  c3 48 83 ec 08 48 63 ff b8 24 00 00 00 0f 05 48  .H...Hc..$.....H
0x7f81dcd33f7f  89 c7 e8 0a 99 fd ff 5a c3 48 83 ec 08 48 63 ff  .......Z.H...Hc.
0x7f81dcd33f8f  48 63 f6 b8 3e 00 00 00 0f 05 48 89 c7 e8 ef 98  Hc..>.....H.....

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

**Comment by How-Bout-No** [comment]
> As soon as I start this version on my server, the server is automatically stopped!

Does it work fine on a fresh FXServer install or is it only when you run it on this particular server?
Make sure you have the latest versions of FXServer, ESX (+ any ESX modules), and mysql-async installed and try running it again.

**Comment by BoutProduction** [comment]
I started it on my test server and it still does not start after updating ESX stuff

**Comment by How-Bout-No** [comment]
Hmmm... I'm unable to replicate this issue, on a completely fresh and brand new install of ESX it seems to work fine :/

I've pushed another update (0414fba) addressing some other issues but test this version out and see if the error persists.

**Comment by BoutProduction** [comment]
[104;39m> SocialSpot <[0;94m
Automatic updates are disabled.
[0m
Assertion failed: m_marks.find(mark) != m_marks.end() (../../../components/citizen-server-impl/src/ResourceFilesComponent.cpp: WriteMark: 35)
Stacktrace:

/proc/self/maps:
406ba000-4075a000 rwxp 00000000 00:00 0
41500000-41510000 rwxp 00000000 00:00 0
41d96000-41e66000 rwxp 00000000 00:00 0
13915a00000-13915a03000 rw-p 00000000 00:00 0
13ca3880000-13ca3900000 rw-p 00000000 00:00 0
17fa8e00000-17fa8e80000 rw-p 00000000 00:00 0
29531500000-29531580000 rw-p 00000000 00:00 0
71574180000-71574200000 rw-p 00000000 00:00 0
aa7ecd00000-aa7ecd80000 rw-p 00000000 00:00 0
b2526300000-b2526303000 rw-p 00000000 00:00 0
b2526303000-b2526380000 r--p 00000000 00:00 0
fefff700000-fefff780000 rw-p 00000000 00:00 0
138ad1f00000-138ad1f80000 rw-p 00000000 00:00 0
1404a2980000-1404a2c1b000 rw-p 00000000 00:00 0
153cc44f3000-153cc4500000 ---p 00000000 00:00 0
153cc4500000-153cc4503000 rw-p 00000000 00:00 0
153cc4503000-153cc4504000 ---p 00000000 00:00 0
153cc4504000-153cc457f000 r-xp 00000000 00:00 0
153cc457f000-153cc4580000 ---p 00000000 00:00 0
153cc4580000-153cc4583000 rw-p 00000000 00:00 0
153cc4583000-153cc4584000 ---p 00000000 00:00 0
153cc4584000-153cc45ff000 r-xp 00000000 00:00 0
153cc45ff000-153cc4600000 ---p 00000000 00:00 0
153cc4600000-153cc4603000 rw-p 00000000 00:00 0
153cc4603000-153cc4604000 ---p 00000000 00:00 0
Memory around native instruction pointer (0x7f2d9a4e8f6f):
0x7f2d9a4e8f5f 00 00 31 d2 bf 02 00 00 00 b8 0e 00 00 00 0f 05 ..1.............
0x7f2d9a4e8f6f c3 48 83 ec 08 48 63 ff b8 24 00 00 00 0f 05 48 .H...Hc..$.....H
0x7f2d9a4e8f7f 89 c7 e8 0a 99 fd ff 5a c3 48 83 ec 08 48 63 ff .......Z.H...Hc.
0x7f2d9a4e8f8f 48 63 f6 b8 3e 00 00 00 0f 05 48 89 c7 e8 ef 98 Hc..>.....H.....

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

**Comment by How-Bout-No** [comment]
Does this happen when `useESXIdentity` is  true or false? Or does it happen either way?

**Comment by BoutProduction** [comment]
I've just written with my hoster, and it has come home that the problem lies with the FiveM version! Once a peson with UTF-8 characters in the name joint crashed the server

**Comment by BoutProduction** [comment]
I hope it works now
